id: configure_api_key
learningObjectives:
  - Configure the connection string for the MongoDB Atlas cluster
hints:
  - In the MongoDB Atlas dashboard, click on 'Connect' for the cluster you've
    created.
  - Follow the instructions to create a user and configure the 'MongoDB
    connection string' for your application.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Good job on creating the cluster!
          - text: Now, we need to create an API key to connect to the cluster.
          - text: In the left hand menu, click on `Services -> Data API`. Then click on `Users` tab and `Create API Key`.
          - text: Give the API key a name and click `Create`.
          - text: Copy the key and paste it here.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_message
  flowNode:
    do:
      - actionId: finish_step