id: configure_connection_string
learningObjectives:
  - Configure the connection string for the MongoDB Atlas cluster
hints:
  - A connection string should include the username and password you chose when creating the cluster, and the cluster name.
  - "The connection string should look like this: `mongodb+srv://<username>:<password>@<cluster-url>/test?retryWrites=true&w=majority`"

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: We should configure a `connection string` for the MongoDB Atlas cluster, so we can connect to it from our application.
          - text: Go to `Security -> Quick start`, :instruction[choose a username and password that will be used in the connection string. **Save the password**, as we will need it soon].
          - text: Next, you should allow access to our app. This is for me to verify you’ve made all the changes that will be required. :instruction[Add the IP `34.192.00.0/16` in the `IP Access List` under `My Local Environment` at the bottom of the page].
          - text: Lastly, go to `Deployment -> Database` tab. There, next to the cluster name, click on `connect` then `Drivers`. Copy the `connection string` format and fill the correct username and password in the placeholders.
          - text: :instruction[Copy the `connection string` and paste it here]
          

trigger:
  type: user_message
  flowNode:
    if:
      conditions:
      - conditionId: text_match_regex
        name: connection_string_prefix
        params:
          text: "${userMessageText}"
          regex: "^mongodb"

      - conditionId: database_check_connection_url
        params:
          type: mongodb
          url: "${userMessageText}"

      then:
        do:
        - actionId: user_set_integration_property
          params:
            integration: mongo
            key: connectionString
            value: ${userMessageText}

        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "That connection string looks good! we are ready to move on to the next step."
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "That's not correct, try again!"
              delay: 500
