id: create_mongo_atlas_cluster
learningObjectives:
  - Create a MongoDB Atlas account and a new cluster
hints:
  - Once logged in, navigate to the 'Clusters' page and create a new one.  

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Welcome to the set of Techtropolis Films.
          - text: At the heart of our universe is MongoDB Atlas, the central reel containing every storyline ever crafted.
          - text: But we've hit a production snag.
          - text: The universe's cinematic harmony is at stake, and only by saving our movie database can we restore balance!
          - text: Ready for your opening scene?
          - text: Visit the producer's lounge at https://www.mongodb.com/cloud/atlas/register to start.
          - text: As the director, you'll be presented with a choice of pricing tiers.
          - text: For your debut, choose the `Cluster Tier` of `M0` – the free tier (to ensure our production doesn't run over budget).
          - text: And while you're in the director's chair, pick your preferred cloud provider and region.
          - text: Next, choose a title for your first movie cluster.
          - text: Once you see your Atlas dashboard, we’ll be ready for action.

    - actionId: ready_message
      params:
        person: lucca

trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: "Great! You've created your first MongoDB Atlas cluster. Let's move on to the next step."
      - actionId: finish_step
