id: create_mongo_atlas_cluster
learningObjectives:
  - Create a MongoDB Atlas account and a new cluster
hints:
  - Once logged in, navigate to the 'Clusters' page and create a new one.  

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Today we are going to learn about MongoDB Atlas, a multi-cloud database service by the same people that build MongoDB. Atlas simplifies deploying and managing your databases while offering the versatility you need to build resilient and performant global applications on the cloud providers of your choice.
          - text: First up, let's create a MongoDB Atlas account so we can create our first Atlas cluster.
          - text: Sign up to Atlas at https://www.mongodb.com/cloud/atlas/register and complete the email verification.
          - text: Next you'll be asked to choose the pricing tier, be sure to choose the free tier, named `M0`.
          - text: Lastly, choose a name for your cluster and any cloud provider and region you'd like.
          - text: Tell me when you're done, that's when you're directed to the Atlas dashboard.

    - actionId: ready_message
      params:
        person: lucca

trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: "Great! You've created your first MongoDB Atlas cluster. Let's move on to the next step."
      - actionId: finish_step
