id: match_query
learningObjectives:
  - Learn how to run a query with numeric values
hints:
  - You can use the `sort` option in the Atlas UI action to sort the results by the `year` field in ascending order.

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Using a Sort, find the oldest movie in the database and delete the document"



trigger:
  type: user_ready_response
  flowNode:
    do:
    - actionId: mongo_query_find
      name: mongo_find_result
      params:
        databaseName: sample_mflix
        collectionName: movies
        uri: "${user.integrations.mongo.connectionString}"
        query:
          title: "The Great Train Robbery"

      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Great! I see you've deleted the correct movie"
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "The oldest movie is still there, try again!"

solution:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "To sort our query using the Atlas UI, we need to use the `More Options` button, that expands a `Sort` option."
          - text: "We can sort the results by the `year` field in ascending order as follows `{year: 1}`. This will return the oldest movie first. "
