id: update_data
learningObjectives:
  - Update data in MongoDB

hints:
  - "Remember, under the studio `anythink`, in the `Movies` collection, lies our distorted reel, [Stephen Hawking’s Universe]. "
  - "Once you find the movie, you'll see the `year` field has the letter `e` in it, which is wrong."
  - "Did you change the `year` to the correct type?"
  - "There are different ways to update the data: the Atlas UI, the MongoDB Compass, or the Mongo API."

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: But wait, we're facing a film glitch, our data is corrupted!
          - text: Our movie, `Stephen Hawking's Universe`, seems to have a film tear.
          - text: The `year` tag on the reel is mislabeled.
          - text: Repair the reel and ensure the film plays seamlessly.

    - actionId: ready_message
      params:
        person: lucca


trigger:
  type: user_ready_response
  flowNode:
    do:
    - actionId: mongo_query_find
      name: mongo_find_result
      params:
        databaseName: anythink
        collectionName: movies
        uri: "${user.integrations.mongo.connectionString}"
        query:
          title: "Stephen Hawking's Universe"

    if:
      conditions:
      - conditionId: is_truthy
        params:
          value: "${outputs.mongo_find_result.data[0]?.year === 2010}"
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Splendid! I've reviewed the reel, and the `year` now correctly showcases 2010. You’ve saved the cinematic universe. For now"
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: I see the issue still exists. Are you sure you fixed it? let's try again.
        - actionId: ready_message
          params:
            person: lucca


solution:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "We can start with searching for the specific document. Using the UI, look for the relevant collection under the `Deployment -> Database` section." 
          - text: "In the query input text box run the query: `{title: \"Stephen Hawking's Universe\"}`. Make sure it returns the correct document."
          - text: "Now, let's fix the malformed data by changing the `year` type to `Int32` and making sure the value is `2010`"
          - text: "Click on `Update` to save the changes."
