id: update_data
learningObjectives:
  - Update data in MongoDB

hints:
  - "Search for the movie `Stephen Hawking's Universe` in the `movies` collection under the `sample_mflix` database."
  - "Once you find the movie, you'll see the `year` field has the letter `e` in it, which is wrong."
  - "Did you change the `year` to the correct type?"
  - "There are different ways to update the data: the Atlas UI, the mongo shell, or the mongo API."

startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "Oh no, I think some of the data is corrupted!"
          - text: "I was told that the `Stephen Hawking's Universe` movie has an issue, because its `year` field is malformed and has a wrong type. It is a year but should be an `Int32`."
          - text: ":instruction[Let me know once the issue is resolved]"
    - actionId: ready_message
      params:
        person: lucca


trigger:
  type: user_ready_response
  flowNode:
    do:
    - actionId: mongo_query_find
      name: mongo_find_result
      params:
        databaseName: sample_mflix
        collectionName: movies
        uri: "${user.integrations.mongo.connectionString}"
        query:
          title: "Stephen Hawking's Universe"

    if:
      conditions:
      - conditionId: is_truthy
        params:
          value: "${outputs.mongo_find_result.data[0]?.year === 2010}"
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: Nice job! I can see the `year` is updated to 2010 now, this will make sure our data is presented correctly.
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: I see the issue is still exists. Are you sure you fixed it? let's try again.
        - actionId: ready_message
          params:
            person: lucca


solution:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: "We can start with searching for the specific document. Using the UI, look for the releveant collection under the `Deployment -> Databse` section." 
          - text: "In the query input text box run the query: `{title: \"Stephen Hawking's Universe\"}". Make sure it returns a signle document.
          - text: "Now, let's fix the malformed data by changing the `year` type to `Int32` and making sure the value is `2010`"
          - text: "Click on `Update` to save the changes."
